### ISSUE TITLE
PTS

### ISSUE THREAD

**Issue by chaiyujin** [phg1024/MultilinearReconstruction#3]
Hi, I'm trying to run your code. It's complied, but I do not known how to get pts file for pictures.
It's very kind of you, if you can offer me a pair of <img, pts>.

**Comment by phg1024** [comment]
pts is a simple txt format of 2D facial landmarks. The function to load the pts files is here: https://github.com/phg1024/MultilinearReconstruction/blob/master/ioutilities.cpp#L82
```
num_points
x1 y1
x2 y2
...
xn yn
```

In the code we use 74 points version following the FaceWarehouse's annotation, but we removed the mouth center point so the multilinear reconstruction code expects 73 points as input.

**Comment by chaiyujin** [comment]
Thank you for information about pts. So far, I run SingleImageReconstruction, and get a `.res` file. How can I visualize the result?
I run the `visualize_mesh`, however, it depends on `B_xxx.obj`. How can I generate these obj files?

**Comment by phg1024** [comment]
You can use the command line option -v: https://github.com/phg1024/MultilinearReconstruction/blob/master/singleimagereconstruction.cpp#L31

**Comment by chaiyujin** [comment]
Thanks a lot.
