### ISSUE TITLE
about albedo_index.png,albedo_pixel.png and face_region_indices.txt

### ISSUE THREAD

**Issue by ahccom** [phg1024/MultilinearReconstruction#6]
Hi,
could you kindly upload the albedo_index.png,albedo_pixel.png and face_region_indices.txt files? Tanks very much.

**Comment by phg1024** [comment]
You can generate these images yourself with the mesh you intend to use: albedo_index.png is the triangle indices map in the texture space, and albedo_pixel.png is the barycentric coordinates map in the texture space.
